config/routes.rb
Rails.application.routes.draw do
  scope "admin/galleries", :module => "breeze/gallery", :name_prefix => "admin_gallery" do
    root :to => "galleries#index"

    resources :galleries do
      resources :images do
        member do
          put :crop
        end
        collection do
          put :reorder
        end
      end
    end
  end
end

app/models/breeze/gallery/gallery.rb
module Breeze
  module Gallery
    class Gallery
      include Mongoid::Document
      identity :type => String

      field :title
      field :description

      field :full_width, type: Integer
      field :full_height, type: Integer
      field :thumb_width, type: Integer
      field :thumb_height, type: Integer
      field :preview_width, type: Integer
      field :preview_height, type: Integer

      has_many_related :images, :class_name => "Breeze::Gallery::Image"

      validates_presence_of :title
      validates_uniqueness_of :title
    end
  end
end

app/models/breeze/gallery/gallery_image.rb
module Breeze
  module Gallery
    class GalleryImage < Breeze::Content::Item

    end
  end
end

app/models/breeze/gallery/image.rb
module Breeze
  module Gallery
    class Image < Breeze::Content::Asset
      field :image_width, :type => Integer
      field :image_height, :type => Integer
      field :position, :type => Integer

      attr_accessor :crop

      belongs_to_related :gallery, :class_name => "Breeze::Gallery::Gallery", :inverse_of => :images

      mount_uploader :file, Breeze::Gallery::GalleryUploader, :mount_on => :file

      before_update :reprocess_file

      scope :ordered, order_by(:position.asc)

      protected
      
        def reprocess_file
          unless crop.blank?

            file.versions.each do |name, v|
              if name.to_s == crop[:version]
                
                file.manipulate! do |image|
                v.manipulate! do |img|
                  img = image.crop(crop[:x].to_i, crop[:y].to_i, crop[:w].to_i, crop[:h].to_i)
                  img.resize!(crop[:width].to_i, crop[:height].to_i)
                  img
                end
                image
                end
              end
            end

        #     target_width, target_height = @crop[:target_width].to_i, @crop[:target_height].to_i
        #   if target_width > 0 && target_height > 0 && (target_width < image_width || target_height || image_height)
        #     w, h = image_width, image_height
            
        #     file.manipulate! do |img|
        #       if r = selection_rect
        #         img.crop! r[:x], r[:y], r[:width], r[:height]
        #         w, h = r[:width], r[:height]
        #       end
              
        #       if target_width > 0 && target_height > 0 && (w > target_width || h > target_height)
        #         if @crop[:mode].to_s == "resize_to_fit" then
        #           img.resize_to_fit! target_width, target_height
        #         else
        #           img.resize_to_fill! target_width, target_height
        #         end
        #       end
              
        #       write_attribute :image_width, img.columns
        #       write_attribute :image_height, img.rows
              
        #       img
        #     end
            
        #     file.versions.each do |name, v|
        #       v.cache! file.file
        #       v.store!
        #     end
        # end

          end
        end
    end
  end
end

app/models/breeze/gallery/instance.rb
module Breeze
  module Gallery
    class Instance < Breeze::Content::Item
      include Breeze::Content::Mixins::Placeable
  
      field :template
      belongs_to_related :gallery, :class_name => "Breeze::Gallery::Gallery"

      TEMPLATES = [ :tour ]

      def self.label
        "Gallery"
      end

      def to_erb(view)
        partial =  "/partials/gallery/#{template}"
        begin
          view.controller.render_to_string :partial => partial, :layout => false, :locals => { :gallery => gallery }
        rescue ActionView::MissingTemplate
          %{<div class="rendering-error"><h3>Missing Template</h3><p>Could not find partial template: #{partial}</p></div>}
        rescue Exception => e
          %{<div class="rendering-error"><h3>#{e.to_s}</h3><p>#{e.message}</p></div>}
        end
      end

#        returning("") do |str|
 #         str << "<div class='gallery'>"
#        gallery.images.each do |image:Ack 
 #           str << "<img src='#{image.file.url(:thumbnail)}' />"
  #        end
   #       str << "</div>"
    #    end
    #  end
    end
  end
end

app/controllers/breeze/gallery/galleries_controller.rb
module Breeze
  module Gallery
    class GalleriesController < Breeze::Admin::AdminController
      def index
        @galleries = Breeze::Gallery::Gallery.order_by([:title, :asc])
      end

      def new
        @gallery = Breeze::Gallery::Gallery.new
      end

      def create
        @gallery = Breeze::Gallery::Gallery.new params[:gallery]
        @gallery.save
      end

      def edit
        @gallery = Breeze::Gallery::Gallery.find params[:id]
      end

      def update
        @gallery = Breeze::Gallery::Gallery.find params[:id]
        @gallery.attributes = params[:gallery]
        @gallery.save
      end

      def destroy
        @gallery = Breeze::Gallery::Gallery.find params[:id]
        @gallery.destroy
      end
    end
  end
end

app/controllers/breeze/gallery/images_controller.rb
module Breeze
  module Gallery
    class ImagesController < Breeze::Admin::AdminController
      def new

      end

      def create
        if (@image = Breeze::Gallery::Image.where(:file => params[:Filename], :folder => params[:folder]).first)
          @image.file, @image.folder = params[:file], params[:folder]
        else
          @image ||= Breeze::Gallery::Image.from_upload params
          @image.gallery_id = params[:gallery_id]
          @image.folder =  "images/galleries/#{@image.gallery.id}/"
          @image.position = @image.gallery.images.count
        end
        @image.save
        respond_to do |format|
          format.html { render :partial => @image.class.name.demodulize.underscore, :object => @image, :layout => false }
          format.js
        end
      end

      def edit
        @image = Breeze::Gallery::Image.find params[:id]
      end

      def destroy
        @image = Breeze::Gallery::Image.find params[:id]
        @image.try :destroy
      end

      def reorder
        params[:image].each_with_index do |id, index|
          Image.find(id).update_attributes :position => index
        end
        render :nothing => true
      end

      def update 
        @image = Breeze::Gallery::Image.find params[:id]
        @image.update_attributes params[:image]
      end

      def crop
        @image = Breeze::Gallery::Image.find params[:id]
        @image.update_attributes params

        render params[:crop][:version]
      end
    end
  end
end

app/views/breeze/gallery/galleries/_form.html.erb
<%= render "/breeze/admin/shared/error_messages", :target => @gallery, :object_name => :gallery %>
<%= form.fieldset do %>
  <%= form.text_field :title %>
  <%= form.text_field :description %>
<% end %>

<% unless @gallery.new_record? %>
  <div id="assets">
    <h3>Images</h3>
    <%= content_tag :div, :class => "assets image-assets" do %>
      <%= render :partial => "breeze/gallery/images/image", :collection => @gallery.images.ordered %>
    <% end %>
  </div>
    
<script type="text/javascript" charset="utf-8">
  $(function() {
      uploadify();

      $('.assets').sortable({
        update: function(e, ui) {
           $.ajax({
             url: '/admin/galleries/galleries/<%= @gallery.id %>/images/reorder.js',
             data: '_method=put&' + $(this).sortable('serialize'),
             type: 'post'
           });
        }
        });
  });
</script>
<% end %>

app/views/breeze/gallery/galleries/_gallery.html.erb
<li id="gallery_<%= gallery.id %>">
<%= link_to "<strong>#{gallery.title}</strong>".html_safe, edit_admin_gallery_gallery_path(gallery), :class => "gallery", :"data-id" => gallery.id %>
</li>

app/views/breeze/gallery/galleries/create.js.erb
<% if @gallery.errors.empty? %>
  close_tab('new_gallery');
  $('#left #galleries').prepend('<%= escape_javascript render(:partial => "gallery", :object => @gallery) %>');
  $('#left #galleries a[data-id=<%= @gallery.id %>]').click();
<% else %>
  $('#gallery_new').replaceWith('<%= escape_javascript render(:template => "/breeze/gallery/galleries/new") %>');
<% end %>

app/views/breeze/gallery/galleries/destroy.js.erb
close_tab('<%= @gallery.id %>');
$('#gallery_<%= @gallery.id %>', '#left #galleries').fadeOut(function() { $(this).remove(); });

app/views/breeze/gallery/galleries/edit.html.erb
<%= breeze_form_for @gallery, :as => :gallery, :url => admin_gallery_gallery_path(@gallery, :format => :js), :remote => true do |form| %>
  <%= scrollable_layout do %>
    <h1>Edit gallery</h1>
    <%= render :partial => "form", :object => form %>
  <% end %>

  <%= content_tag :div, :class => "fake-right-sidebar" do %>
    <%= submit_tag "Save", :class => "large green save button" %>
    <%= link_to "Delete", admin_gallery_gallery_path(@gallery, :format => :js), :method => :delete, :remote => true, :class => "large red delete button" %>
    <%= content_tag :div, :id => "uploader", "data-session-key" => Rails::Application.config.session_options[:key], "data-session-id" => cookies[Rails::Application.config.session_options[:key]] do %>
      <%= link_to "Upload image(s)...", new_admin_gallery_gallery_image_path(@gallery), :class => "large upload button" %>
    <% end %>
  <% end %>
<% end %>

app/views/breeze/gallery/galleries/index.html.erb
<% content_for :title, "Galleries" %>

<% content_for :head do %>
  <%= javascript_include_tag "/breeze/javascripts/galleries" %>
  <%= stylesheet_link_tag "/breeze/stylesheets/gallery" %>

  <%= stylesheet_link_tag "/breeze/javascripts/jcrop/css/jquery.Jcrop.css", "/breeze/javascripts/uploadify/uploadify.css" %>
  <%= javascript_include_tag "/breeze/javascripts/assets", "/breeze/javascripts/jcrop/js/jquery.Jcrop.js", "/breeze/javascripts/uploadify/swfobject.js", "/breeze/javascripts/uploadify/uploadify.js" %>
<% end %>

<%= tabbed_layout do %>

<% end %>

<% content_for :left do %>
  <%= pane_layout do |left| %>
    <% left.header do %>
      <h2>Galleries</h2>
    <% end %>
    <% left.inner do %>
      <ul id="galleries">
        <%= render :partial => "gallery", :collection => @galleries %>
      </ul>
    <% end %>
  <% end %>
<% end %>

<% content_for :right do %>
  <%= pane_layout do |right| %>
    <% right.header do %>
      <%= link_to "New gallery", new_admin_gallery_gallery_path, :class => "large new gallery button" %>
    <% end %>
    <%= right.inner do %>
    <% end %>
  <% end %>
<% end %>

app/views/breeze/gallery/galleries/new.html.erb
<%= breeze_form_for @gallery, :as => :gallery, :url => admin_gallery_galleries_path(:format => :js), :remote => true do |form| %>
  <%= scrollable_layout do %>
    <h1>New gallery</h1>
    <%= render :partial => "form", :object => form %>
  <% end %>
  
  <%= content_tag :div, :class => "fake-right-sidebar" do %>
    <%= submit_tag "Save", :class => "large green save button" %>
  <% end %>
<% end %>

app/views/breeze/gallery/galleries/update.js.erb
<% if @gallery.errors.empty? %>
  $('#left #galleries li a[data-id=<%= @gallery.id %>] strong, a[href=#tab_<%= @gallery.id %>]').text('<%= escape_javascript @gallery.title %>');
  $.flashMessage('This gallery has been updated.', { auto: true });
<% end %>
$('#tab_<%= @gallery.id%>').html('<%= escape_javascript render(:template => "/breeze/gallery/galleries/edit") %>');
renumber_fields('#tab_<%= @gallery.id %>');

app/views/breeze/gallery/images/_image.html.erb
<%= content_tag :div, :class => "image", :id => "image_#{image.id}", :"data-filename" => image.basename, :"data-width" => image.image_width, :"data-height" => image.image_height, :"data-id" => image.id do %>
  <%= content_tag :div, :class => "icon #{image.extension}" do %>
    <%= image_tag image.file.url(:breeze_thumb) %>
  <% end %>
  <%= content_tag :div, :class => :meta do %>
    <span class="filename" title="<%= image.basename %>"><%= truncate image.basename, :length => 22 %></span>
    <small class="dimensions"><%= image.image_width || "??" %> &times; <%= image.image_height || "??" %>, <abbr><%= image.extension %></abbr></small>
  <% end %>
  <%= content_tag :div, :class => :links do %>
    <%= link_to "Edit", edit_admin_gallery_gallery_image_path(image.gallery, image), :class => :edit, :rel => :edit %>
    <%= link_to "Delete", admin_gallery_gallery_image_path(image.gallery, image), :method => :delete, :remote => true, :class => :delete, :rel => :delete %>
  <% end %>
<% end %>

app/views/breeze/gallery/images/crop.js.erb
$('.thumb-current .current').html('<%= image_tag @image.file.url(:thumbnail), :id => :current %>');

app/views/breeze/gallery/images/destroy.js.erb
$('#image_<%= params[:id] %>').fadeOut(function() {
  $(this).remove();
});

app/views/breeze/gallery/images/edit.html.erb
<%= content_tag :div, :class => "gallery-editor" do %>
  <div class="tabs">
    <ul>
      <li><a href="#edit-image">Edit Image</a></li>
      <li><a href="#edit-thumb">Edit Thumb</a></li>
      <% if false %>
        <li><a href="#edit-feature">Edit Feature</a></li>
      <% end %>
    </ul>
    <div id="edit-image">
      <%= content_tag :div, :class => "full-preview" do %>
        <%= content_tag :div, :class => "img" do %>
          <%= image_tag @image.file.url, :width => @image.image_width, :height => @image.image_height %>
        <% end %>
      <% end %>
      <%= form_for @image, :as => :image, :url => admin_gallery_gallery_image_path(@image, :format => :js), :remote => true do |form| %>
        <div class="properties">
          <h3 class="image-name">Title/description</h3>
          <div class="image-name">
            <p><label for="asset_title">Title</label> <%= form.text_field :title %></p>
            <p><label for="asset_description">Description</label> <%= form.text_area :description, :rows => 3 %></p>
          </div>
        </div>
      <% end %>
      <div class="action">
        <p>
          <a href="#" class="large crop button">Crop Full Image</a>
        </p>
        <p>
          <a href="<%= @image.file.url(:full) %>" class="large view button" target="_blank" >View Full Image</a>
        </p>
      </div>
    </div>
    <div id="edit-thumb">
      <div class="full-image">
        <%= image_tag @image.file.url, :id => :thumb %>
      </div>
      <div class="thumb-current">
        <h3>Current Thumb</h3>
        <div class="current" style="<%= "width: #{Breeze::Gallery::GalleryUploader::THUMB_SIZE.width}px; height: #{Breeze::Gallery::GalleryUploader::THUMB_SIZE.height}px" %>">
          <%= image_tag @image.file.url(:thumbnail), :id => :current %>
        </div>
      </div>
      <div class="thumb-preview">
        <h3>Preview (New Thumb)</h3>
        <div class="preview" style="<%= "width: #{Breeze::Gallery::GalleryUploader::THUMB_SIZE.width}px; height: #{Breeze::Gallery::GalleryUploader::THUMB_SIZE.height}px" %>">
          <%= image_tag @image.file.url, :id => :preview %>
        </div>
      </div>
      <div class="action">
        <p>
          <a href="#" class="large crop button">Crop Thumbnail</a>
        </p>
      </div>
    </div>
    <% if false %>
    <div id="edit-feature">
      <div class="full-image">
        <%= image_tag @image.file.url(:full), :id => :feature, :width => @image.image_width, :height => @image.image_height %>
      </div>
      <div class="feature-current">
        <h3>Current Feature</h3>
        <div class="current" style="<%= "width: #{Breeze::Gallery::GalleryUploader::PREVIEW_SIZE.width}px; height: #{Breeze::Gallery::GalleryUploader::PREVIEW_SIZE.height}px" %>">
          <%= image_tag @image.file.url(:preview), :id => :current %>
        </div>
      </div>
      <div class="feature-preview">
        <h3>Preview (New Feature)</h3>
        <div class="preview" style="<%= "width: #{Breeze::Gallery::GalleryUploader::PREVIEW_SIZE.width}px; height: #{Breeze::Gallery::GalleryUploader::PREVIEW_SIZE.height}px" %>">
          <%= image_tag @image.file.url(:full), :id => :preview %>
        </div>
      </div>
      <div class="action">
        <p>
          <a href="#" class="large crop button">Crop Feature</a>
        </p>
      </div>
    </div>
    <% end %>
  </div>
<% end %>

<script type="text/javascript">
  var width = 512;
  var height = 440;

  function showPreview(coords, width, height, selector, api) {
    if (parseInt(coords.w) > 0) {
      var rx = width / coords.w;
      var ry = height / coords.h;
    
      var offset_x = Math.round(rx * coords.x);
      var offset_y = Math.round(ry * coords.y);

      $(selector).css({
        width: Math.round(rx * api.getBounds()[0]) + 'px',
        height: Math.round(ry * api.getBounds()[1]) + 'px',
			  marginLeft: '-' + offset_x + 'px',
			  marginTop: '-' + offset_y + 'px'
        });

      return [coords.x, coords.y, coords.w, coords.h];
    }
  }

function updateThumb(coords) {
    thumb_offset = showPreview(coords, 
        <%= Breeze::Gallery::GalleryUploader::THUMB_SIZE.width %>, 
        <%= Breeze::Gallery::GalleryUploader::THUMB_SIZE.height %>, 
        '.thumb-preview #preview',
        thumb_api);
  }

  function updateFeature(coords) {
    preview_offset = showPreview(coords, 
        <%= Breeze::Gallery::GalleryUploader::PREVIEW_SIZE.width %>, 
        <%= Breeze::Gallery::GalleryUploader::PREVIEW_SIZE.height %>, 
        '.feature-preview #preview',
        feature_api);
  }

  function updateFull(coords) {
    full_offset = showPreview(coords, 
        <%= Breeze::Gallery::GalleryUploader::PREVIEW_SIZE.width %>, 
        <%= Breeze::Gallery::GalleryUploader::PREVIEW_SIZE.height %>, 
        '.feature-preview #previe',
        full_api);
  }

  var thumb_api, preview_api, full_api;
  var first_time_thumb = true;
  var first_time_preview = true;
  var thumb_offset, preview_offset, full_offset;

  function open() {
    $tabs = $('.gallery-editor .tabs').tabs({
      select: function(event, ui) {
      if (ui.index == 1 && first_time_thumb) {
        $('#edit-thumb .full-image img').Jcrop({
          boxWidth: width,
          boxHeight: height,
          onChange: updateThumb,
          onSelect: updateThumb,
          aspectRatio: <%= Breeze::Gallery::GalleryUploader::THUMB_SIZE.aspect_ratio %>
          }, function() {
            thumb_api = this;
          });
          first_time_thumb = false;
        } else if (ui.index == 2 && first_time_preview) {
        $('#edit-feature .full-image #feature').Jcrop({
            boxWidth: width,
            boxHeight: height,
            onChange: updateFeature,
            onSelect: updateFeature,
            aspectRatio: <%= Breeze::Gallery::GalleryUploader::PREVIEW_SIZE.aspect_ratio %>
            }, function() {
              feature_api = this; 
            });
          first_time_preview = false;
          }
        }
    });

        $('.full-preview img').Jcrop({
          boxWidth: width,
          boxHeight: height,
          onChange: updateFull,
          onSelect: updateFull,
          aspectRatio: <%= Breeze::Gallery::GalleryUploader::FULL_SIZE.aspect_ratio %>
          }, function() {
            full_api = this;
          });


    $('#edit-thumb .action a.crop.button').click(function(e) {
        $.ajax({
            url: '/admin/galleries/galleries/<%= @image.gallery_id %>/images/<%= @image._id %>/crop',
             data: '_method=put&crop[version]=thumbnail&crop[width]=<%= Breeze::Gallery::GalleryUploader::THUMB_SIZE.width %>&crop[height]= <%= Breeze::Gallery::GalleryUploader::THUMB_SIZE.height %>&crop[x]=' + thumb_offset[0] + '&crop[y]=' + thumb_offset[1] + '&crop[w]=' + thumb_offset[2] + '&crop[h]=' + thumb_offset[3],
             type: 'post' 
        });
    });

    $('#edit-feature .action a.crop.button').click(function(e) {
      $.ajax({
             url: '/admin/galleries/galleries/<%= @image.gallery_id %>/images/<%= @image._id %>/crop',
             data: '_method=put&crop[version]=preview&crop[width]=<%= Breeze::Gallery::GalleryUploader::PREVIEW_SIZE.width %>&crop[height]= <%= Breeze::Gallery::GalleryUploader::PREVIEW_SIZE.height %>&crop[x]=' + preview_offset[0] + '&crop[y]=' + preview_offset[1] + '&crop[w]=' + preview_offset[2] + '&crop[h]=' + preview_offset[3],
             type: 'post'
           });
      });

    $('#edit-image .action a.crop.button').click(function(e) {
      $.ajax({
             url: '/admin/galleries/galleries/<%= @image.gallery_id %>/images/<%= @image._id %>/crop',
             data: '_method=put&crop[version]=full&crop[width]=<%= Breeze::Gallery::GalleryUploader::FULL_SIZE.width %>&crop[height]=<%= Breeze::Gallery::GalleryUploader::FULL_SIZE.height %>&&crop[x]=' + full_offset[0] + '&crop[y]=' + full_offset[1] + '&crop[w]=' + full_offset[2] + '&crop[h]=' + full_offset[3],
             type: 'post'
           });
    });
  }
</script>

app/views/breeze/gallery/images/full.js.erb
$('#edit-image .full-preview .img').html('<%= image_tag @image.file.url(:full), :style => "max-width: 512px" %>');

app/views/breeze/gallery/images/preview.js.erb
$('.feature-current .current').html('<%= image_tag @image.file.url(:preview), :id => :current %>');

app/views/breeze/gallery/images/thumbnail.js.erb
$('.thumb-current .current').html('<%= image_tag @image.file.url(:thumbnail), :id => :current %>');

app/views/breeze/gallery/images/update.js.erb
$('#image_<%= @image.id %>').replaceWith('<%= escape_javascript render(:partial => "image", :object => @image) %>');
$('#image_edit').closest('.ui-dialog-content').dialog('close').remove();

app/views/breeze/gallery/templates/_gallery.html.erb
<%= form.fieldset do %>
  <%= form.select :gallery_id, Breeze::Gallery::Gallery.all.collect { |g| [ g.title, g._id ] }  %>
  <%= form.select :template, Breeze::Gallery::Instance::TEMPLATES.collect { |t| [ t.to_s.humanize, t ] } %>
<% end %>